kafedra/urls.py
from django.urls import path
from kafedra import views

app_name = 'kafedra_page'

urlpatterns = [
    path(route='auth_kafedra/', view=views.auth, name='auth_kafedra'),
    path(route='profile_kafedra/', view=views.profile, name='profile_kafedra')
]

main_page/urls.py
from django.urls import path
from main_page import views

app_name = 'main_page'

urlpatterns = [
    path('', view=views.index, name='index'),
]

practice_backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
    path('auth_student/', include('student.urls', namespace='student_page')),
    path('profile/', include('student.urls', namespace='student_profile')),
    path('auth_partners/', include('partners.urls', namespace='partners_page')),
    path('profile_part/', include('partners.urls', namespace='partners_profile')),
    path('auth_kafedra/', include('kafedra.urls', namespace='kafedra_page')),
    path('profile_kafedra/', include('kafedra.urls', namespace='profile_kafedra')),
]

student/urls.py
from django.urls import path
from student import views

app_name = 'student_page'

urlpatterns = [
    path(route='auth_student/', view=views.auth, name='auth'),
    path(route='profile/', view=views.profile, name='profile')
]

main_page/models.py
from django.db import models

# Create your models here.

main_page/views.py
from django.contrib.auth import logout
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    logout(request)
    return render(request, 'main_page/index.html')

main_page/templates/main_page/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static 'css/style_index.css' %}">
<title>SUAI</title>

</head>
<body>
    <div class="container" >
        <img src="{% static "image/guap.svg" %}" alt="None">
        <h1 class="label">Производственная практика.</h1>
        <h2 class="label">Здесь Вы можете найти практику на лето за пару кликов</h2>

        <form class="login-form">
            <h2>Для студентов</h2>
            <a href="{% url "student_page:auth" %}" class="login-btn">Войти</a>
        </form>

        <form class="login-form">
            <h2>Для Кафедры</h2>
            <a href="{% url "kafedra_page:auth_kafedra" %}" class="login-btn">Войти</a>
        </form>

        <form class="login-form">
            <h2>Для партнеров</h2>
            <a href="{% url "partners_page:auth" %}" class="login-btn">Войти</a>
            <a href="{% url "main_page:index" %}" class="login-btn">Регистрация</a>
        </form>

    </div>

</body>
</html>